
# build debug version of youki
debug: 
    cargo build
    cp ./target/debug/youki ./youki_bin

# build release version of youki
release:
    cargo build --release
    cp ./target/release/youki ./youki_bin

# clean the generated artifacts
clean:
    rm -f ./youki_bin
    cargo clean